const TASK_GET		= 'TASK_GET';
const TASK_GET_ALL 	= 'TASK_GET_ALL';
const TASK_ADD 		= 'TASK_ADD';
const TASK_EDIT 	= 'TASK_EDIT';
const TASK_REMOVE 	= 'TASK_EDIT';
const TASK_CHANGE_STATUS 	= 'TASK_CHANGE_STATUS';

module.exports = {
	TASK_GET,
	TASK_GET_ALL,
	TASK_ADD,
	TASK_EDIT,
	TASK_REMOVE,
	TASK_CHANGE_STATUS
};